# Generated by Django 4.2 on 2023-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_products_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
