# Generated by Django 4.2 on 2023-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_alter_cartitem_cart_alter_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
