# Generated by Django 4.2 on 2023-07-26 23:54

import customadmin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_useraddress_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(default=customadmin.models.Orders.generate_ordernum, max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('card', 'Debit/Credit card'), ('cod', 'Cash on delivery'), ('net_banking', 'Internet Banking'), ('upi', 'Pay using UPI app')], default='Cash on delivery', max_length=100)),
                ('order_status', models.CharField(choices=[('processing', 'Procrssing'), ('delivered', 'Delivered'), ('out', 'Out of delivery'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('shipped', 'Shipped'), ('pending', 'Pending')], default='Procrssing', max_length=100)),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.variants')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.orders')),
            ],
        ),
    ]
