# Generated by Django 4.2 on 2023-07-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_orders_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sold_at_price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.variants')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_of_user', to='customadmin.userprofile'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Procrssing'), ('delivered', 'Delivered'), ('out', 'Out of delivery'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('pending', 'Pending')], default='Procrssing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_of_user', to='customadmin.userprofile'),
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_order', to='customadmin.orders'),
        ),
    ]
