# Generated by Django 4.2 on 2023-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_orderitems_alter_cart_user_alter_orders_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cancel_req',
            field=models.BooleanField(default=False),
        ),
    ]
