# Generated by Django 4.2 on 2023-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_orderitems_cancel_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_order_status',
            field=models.CharField(choices=[('processing', 'Procrssing'), ('delivered', 'Delivered'), ('out', 'Out of delivery'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('pending', 'Pending')], default='Procrssing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Procrssing'), ('complete', 'Complete'), ('shipped', 'Shipped'), ('pending', 'Pending')], default='Procrssing', max_length=100),
        ),
    ]
