# Generated by Django 4.2 on 2023-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_rename_address_ine2_useraddress_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
