# Generated by Django 4.2 on 2023-07-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_baseproduct_variantimages_remove_product_category_and_more'),
    ]

    operations = [
    ]
