# Generated by Django 4.2 on 2023-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_coupons_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupon_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='min_spend',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
