# Generated by Django 4.2 on 2023-07-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_variants_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='name',
            new_name='variantname',
        ),
    ]
