# Generated by Django 4.2 on 2023-08-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_coupons_coupon_amount_coupons_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupons',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
