# Generated by Django 4.2 on 2023-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_auto_20230723_0723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseProduct',
            new_name='BaseProducts',
        ),
        migrations.RenameModel(
            old_name='Variant',
            new_name='Variants',
        ),
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
