# Generated by Django 4.2 on 2023-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_remove_usercoupon_coupon_remove_usercoupon_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=8)),
                ('min_spend', models.PositiveIntegerField()),
                ('coupon_discount', models.PositiveIntegerField()),
                ('max_discount', models.PositiveIntegerField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
