# Generated by Django 4.2 on 2023-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='coupon_discount',
            new_name='coupon_discount_percent',
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_type',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], default='None', max_length=50),
            preserve_default=False,
        ),
    ]
