# Generated by Django 4.2 on 2023-08-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_rename_coupon_discount_coupons_coupon_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customadmin.coupons'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=50, null=True),
        ),
    ]
