# Generated by Django 4.2 on 2023-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0016_cart_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
