# Generated by Django 4.2 on 2023-08-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0017_coupons_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
