# Generated by Django 4.2 on 2023-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0018_alter_coupons_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
