# Generated by Django 4.2 on 2023-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_alter_coupons_coupon_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
