# Generated by Django 4.2 on 2023-08-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0020_orders_coupon_discount_orders_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupon_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UsedCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_used', to='customadmin.userprofile')),
            ],
        ),
    ]
