# Generated by Django 4.2 on 2023-08-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0021_coupons_coupon_count_usedcoupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='coupon_count',
        ),
    ]
