# Generated by Django 4.2 on 2023-08-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0022_remove_coupons_coupon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_discount_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='max_discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='min_spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='sold_at_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='coupon_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usedcoupons',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.coupons'),
        ),
    ]
