# Generated by Django 4.2 on 2023-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='min_spend',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='sold_at_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='coupon_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
