# Generated by Django 4.2.4 on 2023-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0026_rename_item_wsihitems_variant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WsihItems',
            new_name='WishItems',
        ),
    ]
