# Generated by Django 4.2.4 on 2023-08-18 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0028_orderaddresshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
